version: "3.8"

services:
  wikiscraper:
    build: .
    volumes:
      - .:/app  # Monta el directorio actual en /app dentro del contenedor
    working_dir: /app  # Establece el directorio de trabajo en /app
    stdin_open: true  # Mantiene la entrada estándar abierta
    tty: true  # Activa el modo interactivo
    environment:
      - PYTHONPATH=/app/src  # Establece PYTHONPATH
    command: /bin/bash  # Ejecuta bash por defecto
